#!/bin/bash
# makes *.tex file with selected problems
# produces pdf and shows it with VIEWER

FILE=sel_tags

id=("$@")
rm $FILE.tex
touch $FILE.tex 
cat "header.tex" >> $FILE.tex 

for index in $(seq 0 $((${#id[@]}-1)))
do
    echo "\setcounter{notask}{${id[$index]}}" >> $FILE.tex
    cat "problems/${id[$index]}.tex" >> $FILE.tex
    echo -e "\n" >> $FILE.tex
done

echo "\end{document}" >> $FILE.tex
pdflatex -synctex=1 $FILE.tex
xdg-open $FILE.pdf &