#!/bin/bash
# добавляем \end{document} к файлу с отобранными задачами и компилируем его

FILE=sel_id

echo "\end{document}" >> $FILE.tex

pdflatex -synctex=1 $FILE.tex
./pdb-open $FILE.pdf &

if [ -n "$1" ]
    then
    cp $FILE.tex $1.tex
    cp $FILE.pdf $1.pdf
fi
