* Описание.

База олимпиадных задач по физике с интерфейсом для поиска по ключевым
словам. 

* Требования.

1. =Linux=. 

2. =bash= или =zsh=.

3. =texlive=.

* Установка. 

1. Скачайте [[https://github.com/shender/pdb/zipball/master][zip–файл]] со всеми скриптами и задачами (или клонируйте
   этот репозиторий — если вы знаете, как это делается).

2. Распакуйте его в выбранном вами месте.

* Настройка. 

Для того, чтобы заработало автодополнение при выборе ключевых слов,
допишите в файл =~/.bash_profile= (или =~/.bashrc=) строчку

#+BEGIN_EXAMPLE
. $HOME/путь_к_папке_pdb/pdb-find-completion
#+END_EXAMPLE

Возможно, придётся разлогиниться и залогиниться снова. 

Любители =zsh= дописывают в =~/.zshrc=

#+BEGIN_EXAMPLE
_pdb-find-completion() {
    reply=( $(cat ./tags) )
}
compctl -K _pdb-find-completion ./pdb-find
#+END_EXAMPLE

и также перелогиниваются.

* Описание процесса работы с базой.

1. Перед началом поиска необходимо выполнить =./pdb-init=. Это
   требуется для очистки результатов предыдущего поиска.

2. Для поиска задач по ключевым словам надо выполнить =./pdb-find tag1
   tag2 ...=, где =tag1=, =tag2= ... — ключевые слова, по которым ведётся
   поиск. Ищутся задачи, которые подходят по совокупности ключевых
   слов, т.е. между ключевыми словами стоит «И». Список всех
   существующих ключевых слов есть в файле =tags=.
   
   Пример: =./pdb-find электричество схема= — поиск по задачам на
   электричество, в которых дана какая-то схема.

3. Скрипт напишет, сколько задач удовлетворяет данному критерию,
   сделает из найденных задач промежуточный pdf–файл и покажет его
   вам. В этом файле номер рядом с задачей соответствует её номеру в
   базе данных.

4. Изучите pdf–файл. Добавьте интересующие вас задачи в итоговый файл
   с помощью команды =./pdb-add id1 id2 id3 ...=, где =id1=, =id2=,
   =id3=,... — номера задач.
   
   Пример: =./pdb-add 1 5 21= добавит в файл 1-ю, 15-ю и 21-ю
   задачи.

5. Повторяйте шаги 2–4 пока не наберёте столько задач, сколько
   нужно. На каждом этапе добавления задач скрипт сообщит, сколько уже
   задач отобрано.

6. Выполните =./pdb-compile=, чтобы получить итоговый pdf–файл с
   задачами. Получившийся файл автоматически отобразится в вашем
   просмотрщике pdf–файлов.
   
   Запуск этой команды с аргументом =./pdb-compile ИМЯ= приведёт к
   тому, что будут созданы итоговые файлы =ИМЯ.tex= и =ИМЯ.pdf=.
   
